### ISSUE TITLE
Изменить формулировку

### ISSUE THREAD

**Issue by MaximGrynykha** [bzick/oh-my-backend#16]
https://github.com/bzick/oh-my-backend/edit/master/README.md#L10

`------------------------------------------------------------------------------------------------------------------`
`СЕЙЧАС:` Принцип работы пункта будет дополнительным бонусом в понимании темы, но это может занять много времени. Изучайте по желанию и необходимости.
`ИЗМЕНИТЬ НА:` Понимание принципа работы каждого пункта будет дополнительным бонусом в понимании всей темы, но это может занять много времени. Изучайте по желанию и необходимости.

https://github.com/bzick/oh-my-backend/edit/master/README.md#L259
`------------------------------------------------------------------------------------------------------------------`
`СЕЙЧАС:` Изучить придётся только если придётся создавать свой протокол передачи данных взамен изжившего себя TCP.
`ИЗМЕНИТЬ НА:` Изучить придётся только если потребуется создать свой протокол передачи данных взамен изжившего себя TCP.

**Comment by bzick** [comment]
изменено
