### ISSUE TITLE
Неоднозначность формулировки

### ISSUE THREAD

**Issue by MaximGrynykha** [bzick/oh-my-backend#17]
`------------------------------------------------------------------------------------------------------------------`
https://github.com/bzick/oh-my-backend/edit/master/README.md#L16
`СЕЙЧАС:` Ссылка на вики ставятся что бы исключить ошибочного варианта статьи на вики.

`------------------------------------------------------------------------------------------------------------------`
https://github.com/bzick/oh-my-backend/edit/master/README.md#L250
`И их работа и скорость передачи напорямую влияет на скорость передачу данных` -> `?`

**Comment by bzick** [comment]
- перефразировал
- убрал
