### ISSUE TITLE
Предложение об изменении формулировки

### ISSUE THREAD

**Issue by MaximGrynykha** [bzick/oh-my-backend#18]
https://github.com/bzick/oh-my-backend/edit/master/README.md#L52

`СЕЙЧАС:` ...всё равно поднимите виртуализацию.

`ПРЕДЛОЖЕНИЕ:` ...всё равно, виртуализируйте рабочее пространство. (или - создайте виртуализацию рабочего пространства)

**Comment by bzick** [comment]
Там неуместное предложение про линкус. Мы про него вообще еще ничего не упоминали, а уже что-то втираем про линукс. Причем это касаемо и для bsd систем. Так что решил убрать это предложение. Повествование не нарушилось.
